### ISSUE TITLE
Firefox Addon *Does* work on Android

### ISSUE THREAD

**Issue by Grossdm** [Impactstory/oadoi#111]
I have tested the addon in both the Release and Beta versions of Fennec.

I actually didn't realize that it was "flagged" as Desktop only until I noticed that I had not yet installed it in Fennec Release - I assume that I forwarded the AMO link from a Desktop install to Fennec Beta, bypassing the Android version of AMO.

Please confirm my experience by using the [Desktop AMO Link](https://addons.mozilla.org/firefox/addon/unpaywall) from Firefox for Android.

Thank you very much for the addon!

Doug

**Comment by jasonpriem** [comment]
Thanks for the comment! I'm very sorry, but I'm a little confused...what specifically would you like us to do?

**Comment by Grossdm** [comment]
Tell AMO to allow the addon to be listed for mobile devices, please.

**Comment by hpiwowar** [comment]
The problem is it only works on Android Firefox, not iPhone Firefox, so we
we've decided to err conservative in our reporting.

--
Heather Piwowar, cofounder
Impactstory <http://impactstory.org/>: We make tools to power the Open
Science revolution
follow at @researchremix <https://twitter.com/researchremix>, @impactstory
<http://twitter.com/impactstory>, and @unpaywall
<https://twitter.com/unpaywall>

**Comment by Grossdm** [comment]
Interesting.
From Fennec, AMO directs to not mobile vs. desktop but platform-specific URLs.

For example, `https://addons.mozilla.org/addons/en-US/android/...`.

It looks like AMO should be able to allow an addon for Android vs. Apple - or vice versa.

**Comment by richard-orr** [comment]
Moved to https://support.unpaywall.org/public/tickets/06671dfa8e156f98828a133b55694be259b0c4e075ef39f3902471729600e9dc
