### ISSUE TITLE
False negative for a Elsevier AGIC journal

### ISSUE THREAD

**Issue by nemobis** [Impactstory/oadoi#29]
https://doi.org/10.1016/j.ajic.2015.12.024 is available without login at http://www.ajicjournal.org/article/S0196-6553(16)00002-X/pdf but http://api.oadoi.org/10.1016/j.ajic.2015.12.024 says it's closed. BASE doesn't index any such paper although they have a collection for Elsevier open access https://www.base-search.net/Search/Results?q=dccoll:crelsevierbv&refid=dctableen

**Comment by ioverka** [comment]
That's an "interesting" case because the letters to the editor are free to read only via the original/specific journal homepage but not via ScienceDirect, see:

![sciencedirect-noaccess](https://user-images.githubusercontent.com/8920469/30067686-baf09f60-925b-11e7-93c7-486b1d01a1f8.png)

To me it looks like the content hasn't been published under an Open Access license explicitly, but the public availability is a temporary (?) gift by the publisher. This is how a "real" Open Access article looks like (from the same issue):

![sciencedirect-oa](https://user-images.githubusercontent.com/8920469/30067711-ce361bf4-925b-11e7-875d-0eef28ec4c76.png)

oaDOI works fine for the second example, see http://api.oadoi.org/10.1016/j.ajic.2015.12.018 - because the license information has been deposited at Crossref, see http://api.crossref.org/works/10.1016/j.ajic.2015.12.018. According to my knowledge, BASE also uses Crossref for its Elsevier open access collection.

What do you think: Are "letter to editors" worth the effort to try to convince Elsevier to distribute information about  the free availability (via Crossref - preferably)?

**Comment by nemobis** [comment]
> What do you think: Are "letter to editors" worth the effort to try to convince Elsevier to distribute information about the free availability (via Crossref - preferably)?

Probably not, in themselves. But many journals seem to have some sections/columns whose items get distributed for free, so it would be nice to fix the problem systematically.
