### ISSUE TITLE
question: how to trigger metadata update after modification on https://hal.archives-ouvertes.fr/?

### ISSUE THREAD

**Issue by monperrus** [Impactstory/oadoi#62]
When I update some metadata on https://hal.archives-ouvertes.fr/, in particular the doi or the url field, how can I make sure that the oadoi crawler sees the change?

**Comment by monperrus** [comment]
ping?

**Comment by hpiwowar** [comment]
Hi!  Yup, thanks for your patience.  We haven't forgotten.  We've been busy
raising money so we can [hire another developer](
http://blog.impactstory.org/hiring-lead-dev/) to expand our 2 person team,
so we can be more responsive to github issues in the future :)
If you know anybody great, let us know, otherwise we'll get to this as soon
as we can.
Best,
Heather

--
Heather Piwowar, cofounder
Impactstory <http://impactstory.org/>: We make tools to power the Open
Science revolution
follow at @researchremix <https://twitter.com/researchremix>, @impactstory
<http://twitter.com/impactstory>, and @unpaywall
<https://twitter.com/unpaywall>

**Comment by monperrus** [comment]
Hi Heather,

Thanks for your answer.

Does this mean that oadoi.org may stop delivering service in the short or in the mid-term?

**Comment by hpiwowar** [comment]
No not at all.  I just meant to say we've just been slow to look into this bug, and we'll be able to look into bugs more quickly in the future.

**Comment by monperrus** [comment]
OK. I look forward to your answer, in order to reach a 100% open-access ratio on oadoi :)

**Comment by richard-orr** [comment]
As long as the record's [datestamp](http://www.openarchives.org/OAI/openarchivesprotocol.html#SelectiveHarvestingandDatestamps) is updated when the metadata changes, we'll puck up the change.
